services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--entrypoints.qubed.address=:${PUBLIC_PORT}"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
    ports:
      - "${PUBLIC_PORT}:${PUBLIC_PORT}"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    env_file:
      - .env
    volumes:
      - "./letsencrypt:/letsencrypt"
      - ./dynamic.yml:/configuration/dynamic.yml:ro
    networks:
      - main
  
  frontend:
    build: ./frontend
    expose:
        - 8081
    networks:
      - main
  
  backend:
    build: ./backend
    expose:
        - 8080
    networks:
      - main

networks:
    main:
